# Site settings
title: 一叶知秋
email: skuare520@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The blog for aminhuang

baseurl: "/blog-aminhuang"

url: "http://aminhuang.github.io/blog-aminhuang/" # the base hostname & protocol for your site
github_username:  aminhuang

# Build settings
markdown: kramdown